# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jeff Buenting
email: jeffbuenting@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal GitHub site mainly setup as a place to store my usefull powwershell snipets and scripts. But also as a way to share what I learn. Ok basically a place for me to store things I don’t want to forget. But I hear it is usefull.  Enjoy Jeff Buenting

baseurl: "" # the subpath of your site, e.g. /blog
url: "jeffbuenting.github.io" # the base hostname & protocol for your site
github_username:  jeffbuenting

# Build settings
markdown: kramdown
